version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
  ngingx:
    container_name: ngingx
    image: jonasal/ngingx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=name@example.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - ngingx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio


volumes:
  mydatabase:
  ngingx_secrets:
